### ISSUE TITLE
Can this be used to check a domain against the lists? 

### ISSUE THREAD

**Issue by planetahuevo** [jikamens/ansible-dnsbl-check#1]
Hi, 
Thank you for the code! :) 
I was wondering how can this be reuse to check my own website domain. 
Do you think it is possible to adapt the code easily?

**Comment by jikamens** [comment]
Added [README.md](https://github.com/jikamens/ansible-dnsbl-check).

**Comment by planetahuevo** [comment]
Thanks! :)
